import { Metadata } from "next";
export const metadata: Metadata = {
    title: "Bảng thưởng phạt",
    description: "Generated by create next app",
  };
  
  export default function UserLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <div>
          {children}
          </div>
    );
  }