import Employee from "@/components/employees";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "Employees",
    description: "Generated by create next app",
  };
  
  export default function EmployeeLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <div>
          <Employee/>
          {children}
          </div>
    );
  }
  