import Dashboard from "@/components/dashboard";
import { Metadata } from "next";
import Header from "@/components/header"
export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
  };
  
  export default function Layout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <div>
          <Dashboard/>
          {children}
          </div>
    );
  }
  