import AdminDashboard from "@/components/admin/dashboard";

import { Metadata } from "next";
export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
  };
  
  export default function Layout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <div>
          <AdminDashboard/>
          {children}
          </div>
    );
  }
  